### ISSUE TITLE
Validate multiple fields for @SameCurrency

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/money-validation#1]
Add a (class-level) validation that checks multiple fields for using the same currency. Make this group-able. See @jhorstmann idea.

    @SameCurrency(DomesticCurrency.class)
    @SameCurrency(BaseCurrency.class)
    public class SalesOrder {

**Comment by whiskeysierra** [comment]
Just for clarification: Based on the example, `DomesticCurrency` and `BaseCurrency` are annotation types themselves and used on specific fields respectively, like this?

    @SameCurrency(DomesticCurrency.class)
    @SameCurrency(BaseCurrency.class)
    public class SalesOrder {

        @DomesticCurrency
        private MonetaryAmount grandTotal;

        @BaseCurrency
        private MonetaryAmount accountingGrandTotal;

    }

**Comment by whiskeysierra** [comment]
I'm closing this for now due to 1y inactivity.
